apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dxu8qkc20-python
  janus-idp.io/tekton: dxu8qkc20-python
  backstage.io/kubernetes-id: dxu8qkc20-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dxu8qkc20-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
