apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dxu8qkc20-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dxu8qkc20-python 
  name: dxu8qkc20-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dxu8qkc20-python 
